from .admin_handlers import register_admin_handler
from .private_user_handlers import register_privat_user_handlers
from .user_handlers import register_user_handlers
from .heandlers_tasks import register_time_task_handler