name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
            BASE_URL_WEATHER: ${{ secrets.BASE_URL_WEATHER }}
            API_WEATHER: ${{ secrets.API_WEATHER }}
            ADMIN_IDS: ${{ secrets.ADMIN_IDS }}
          run: docker build . --file Dockerfile --tag mirabot:$(date +%s)
